/**
 * Sprint D #3 — Redeploy MagnetaOFTStandardFactory on one chain.
 *
 * The factory was shrunk under the Spurious Dragon limit (24572/24576
 * bytes, see SPRINT_D_3_FACTORY_AUTO_REGISTER.md) and now auto-calls
 * TokenOpsModule.registerByTokenOwner in createOFTStandardToken /
 * createForCreator. We redeploy on each of the 19 LZ-V2 chains so users
 * stop hitting "TokenNotRegistered" 0x259ba1ad when they try MINT /
 * UPDATE / FREEZE on a fresh token from the Magneta-managed UI.
 *
 * Per-chain flow (model: deployLPModuleSafe.ts + deployCronosReceiver.ts):
 *
 *   1. Deploy new MagnetaOFTStandardFactory(treasury, lzEndpoint).
 *      The new factory's Ownable() constructor sets the deployer EOA
 *      as initial owner.
 *   2. Transfer ownership to the chain's in-house OR Safe Wallet UI
 *      Safe in a single deployer tx (factory uses OZ 4.x Ownable, no
 *      acceptOwnership second leg).
 *   3. Generate a Safe batch (scripts/safe/<chain>-d3-redeploy-batch.json)
 *      containing the 3 wiring calls the Safe must sign:
 *        - factory.setTokenOpsModule(localTokenOps)
 *        - factory.setCrossChainCreator(localDispatcher)
 *        - dispatcher.setStandardFactory(newFactory)
 *   4. Archive the previous factory address in deployments-oft/<chain>.json
 *      under MagnetaOFTStandardFactory_old (or _old_N if there's already
 *      a prior archive — same idempotent pattern as
 *      redeployLPModule.ts in the contracts repo).
 *
 * Usage:
 *   pnpm hardhat run scripts/redeploy-oft-std-factory.ts --network polygon
 *   ... per chain, 19 total (excluding Cronos which has no LZ V2)
 *
 * After all 19 are done, generate the gatewayChains.ts patch via:
 *   pnpm tsx scripts/print-d3-frontend-patch.ts
 * (the printer is generated by THIS script's final `console.log`)
 */
import { ethers, network } from "hardhat";
import fs from "node:fs";
import path from "node:path";
import { CHAIN_CONFIG } from "./chainConfig";

const REPO_ROOT = path.join(__dirname, "..");
const OFT_DIR = path.join(REPO_ROOT, "deployments-oft");
const DISPATCHER_DIR = path.join(REPO_ROOT, "deployments-dispatcher");
const BATCH_DIR = path.join(REPO_ROOT, "scripts", "safe");

// Frontend gatewayChains.ts is where the tokenOpsModule address lives
// per chain (these match the on-chain Gateway.moduleFor(MINT=4) — see
// __tests__/integration/frontendOnChainParity.test.ts cross-repo
// audit). Read by simple grep, not import, so the redeploy script
// can run from the contracts/solidity hardhat workspace without
// pulling the whole tokens app TypeScript graph.
function readTokenOpsModuleFromFrontend(chainId: number): string {
  const front = path.resolve(REPO_ROOT, "..", "..", "lib", "constants", "gatewayChains.ts");
  if (!fs.existsSync(front)) {
    throw new Error(`Frontend gatewayChains.ts not found at ${front}`);
  }
  const text = fs.readFileSync(front, "utf-8");
  const line = text.split("\n").find((l) => l.match(new RegExp(`^\\s+${chainId}:`)));
  if (!line) throw new Error(`No frontend entry for chainId ${chainId}`);
  const match = line.match(/tokenOpsModule:\s+'([^']+)'/);
  if (!match) throw new Error(`No tokenOpsModule in frontend entry for ${chainId}`);
  return match[1];
}

interface OFTDeploymentRecord {
  network: string;
  chainId: string;
  deployer: string;
  treasury: string;
  lzEndpoint: string;
  timestamp: string;
  factories: {
    MagnetaOFTStandardFactory: string;
    MagnetaOFTAutoLiquidityFactory: string;
    [key: string]: string;
  };
  createTokenDispatcher?: string;
  safe?: string;
  notes?: string[];
}

async function main() {
  const [deployer] = await ethers.getSigners();
  const net = await ethers.provider.getNetwork();
  const chainId = Number(net.chainId);

  console.log(`\n── Sprint D #3 — MagnetaOFTStandardFactory redeploy ──`);
  console.log(`Network    : ${network.name} (chainId ${chainId})`);
  console.log(`Deployer   : ${deployer.address}`);

  const cfg = CHAIN_CONFIG[chainId];
  if (!cfg) throw new Error(`No chain config for chainId ${chainId}`);
  if (cfg.lzEndpoint === null) {
    console.log(`\n⚠ Skipping ${network.name} — no LZ V2 endpoint (Cronos pattern).`);
    return;
  }

  // ─── Read prior deployment state ───────────────────────────────────────
  const oftPath = path.join(OFT_DIR, `${network.name}.json`);
  if (!fs.existsSync(oftPath)) {
    throw new Error(`No prior OFT deployment at ${oftPath} — run deploy-oft-factories.ts first.`);
  }
  const oftDep = JSON.parse(fs.readFileSync(oftPath, "utf-8")) as OFTDeploymentRecord;

  const dispatcherPath = path.join(DISPATCHER_DIR, `${network.name}.json`);
  if (!fs.existsSync(dispatcherPath)) {
    throw new Error(`No dispatcher deployment at ${dispatcherPath} — run deploy-create-token-dispatcher.ts first.`);
  }
  const dispatcherDep = JSON.parse(fs.readFileSync(dispatcherPath, "utf-8"));
  const dispatcherAddr = dispatcherDep.createTokenDispatcher as string;
  const safeAddr = dispatcherDep.safe as string;
  if (!dispatcherAddr || !safeAddr) {
    throw new Error(`dispatcher.json missing createTokenDispatcher or safe`);
  }

  const tokenOps = readTokenOpsModuleFromFrontend(chainId);
  const oldFactory = oftDep.factories.MagnetaOFTStandardFactory;

  console.log(`   Old factory  : ${oldFactory}`);
  console.log(`   Dispatcher   : ${dispatcherAddr}`);
  console.log(`   Safe (Gateway/dispatcher owner): ${safeAddr}`);
  console.log(`   Treasury     : ${cfg.treasury}`);
  console.log(`   LZ endpoint  : ${cfg.lzEndpoint}`);
  console.log(`   TokenOps (frontend): ${tokenOps}`);

  // ─── Pre-flight checks ─────────────────────────────────────────────────
  const balance = await ethers.provider.getBalance(deployer.address);
  console.log(`   Deployer bal : ${ethers.formatEther(balance)} native`);
  if (balance === 0n) throw new Error("Deployer has 0 balance — fund it first");

  // Sanity: dispatcher must currently be owned by the Safe (Sprint B
  // transferred ownership via setDelegate batches; if a chain wasn't done
  // yet, the setStandardFactory call in the batch would fail).
  const dispatcher = await ethers.getContractAt(
    [
      "function owner() view returns (address)",
      "function standardFactory() view returns (address)",
      "function setStandardFactory(address)",
    ],
    dispatcherAddr,
  );
  const dispOwner = await dispatcher.owner();
  if (dispOwner.toLowerCase() !== safeAddr.toLowerCase()) {
    throw new Error(
      `Dispatcher owner ${dispOwner} != Safe ${safeAddr}. ` +
      `Did Sprint B finish on ${network.name}?`,
    );
  }
  const dispStdFactory = await dispatcher.standardFactory();
  if (dispStdFactory.toLowerCase() !== oldFactory.toLowerCase()) {
    console.log(
      `   ⚠ dispatcher.standardFactory ${dispStdFactory} ≠ frontend's old factory ${oldFactory}. ` +
      `Proceeding (Safe batch will update dispatcher), but flag in PR.`,
    );
  }

  // ─── Deploy new factory ───────────────────────────────────────────────
  console.log(`\n── Deploying new MagnetaOFTStandardFactory…`);
  const Factory = await ethers.getContractFactory("MagnetaOFTStandardFactory");
  const factory = await Factory.deploy(cfg.treasury, cfg.lzEndpoint);
  await factory.waitForDeployment();
  const newFactory = await factory.getAddress();
  console.log(`   ✓ New factory deployed: ${newFactory}`);

  // ─── Transfer ownership to Safe ───────────────────────────────────────
  console.log(`── Transferring factory ownership to Safe ${safeAddr}…`);
  const factoryOwnable = await ethers.getContractAt(
    ["function transferOwnership(address)", "function owner() view returns (address)"],
    newFactory,
  );
  const tx = await factoryOwnable.transferOwnership(safeAddr);
  await tx.wait();
  const finalOwner = await factoryOwnable.owner();
  console.log(`   ✓ owner = ${finalOwner}`);

  // ─── Update deployments-oft/<chain>.json ──────────────────────────────
  let archiveKey = "MagnetaOFTStandardFactory_old";
  let n = 2;
  while (oftDep.factories[archiveKey]) archiveKey = `MagnetaOFTStandardFactory_old_${n++}`;
  oftDep.factories[archiveKey] = oldFactory;
  oftDep.factories.MagnetaOFTStandardFactory = newFactory;
  oftDep.timestamp = new Date().toISOString();
  oftDep.notes = (oftDep.notes ?? []) as string[];
  oftDep.notes.push(
    `${new Date().toISOString().slice(0, 10)} — Sprint D #3 redeploy. ` +
    `Prior factory at ${archiveKey} = ${oldFactory}. ` +
    `Wire via scripts/safe/${network.name}-d3-redeploy-batch.json.`,
  );
  fs.writeFileSync(oftPath, JSON.stringify(oftDep, null, 2));
  console.log(`   ✓ Updated ${oftPath}`);

  // ─── Generate Safe batch ──────────────────────────────────────────────
  const factoryIface = new ethers.Interface([
    "function setTokenOpsModule(address)",
    "function setCrossChainCreator(address)",
  ]);
  const dispatcherIface = new ethers.Interface([
    "function setStandardFactory(address)",
  ]);

  const transactions = [
    {
      to: newFactory,
      value: "0",
      data: factoryIface.encodeFunctionData("setTokenOpsModule", [tokenOps]),
      contractMethod: null,
      contractInputsValues: null,
    },
    {
      to: newFactory,
      value: "0",
      data: factoryIface.encodeFunctionData("setCrossChainCreator", [dispatcherAddr]),
      contractMethod: null,
      contractInputsValues: null,
    },
    {
      to: dispatcherAddr,
      value: "0",
      data: dispatcherIface.encodeFunctionData("setStandardFactory", [newFactory]),
      contractMethod: null,
      contractInputsValues: null,
    },
  ];

  const batch = {
    version: "1.0",
    chainId: String(chainId),
    createdAt: 1780500000,
    meta: {
      name: `Magneta Sprint D #3 wire — ${network.name}`,
      description:
        `Sprint D #3 redeploy of MagnetaOFTStandardFactory. ` +
        `Wires the new factory (${newFactory}) so cross-chain CREATE_TOKEN ` +
        `lands on it AND the new factory auto-registers freshly-minted ` +
        `tokens with TokenOpsModule (${tokenOps}) so users can MINT/UPDATE/ ` +
        `FREEZE without an extra registerByTokenOwner tx. Sign with ` +
        `Safe ${safeAddr}.`,
    },
    transactions,
  };

  if (!fs.existsSync(BATCH_DIR)) fs.mkdirSync(BATCH_DIR, { recursive: true });
  const batchPath = path.join(BATCH_DIR, `${network.name}-d3-redeploy-batch.json`);
  fs.writeFileSync(batchPath, JSON.stringify(batch, null, 2));
  console.log(`   ✓ Safe batch: ${batchPath}`);

  console.log(`\n── NEXT STEPS ──`);
  console.log(`1. Copy batch + execute via the appropriate execBatch path:`);
  console.log(`     cp ${path.relative(process.cwd(), batchPath)} ../../../magneta-finance-contracts/scripts/safe/`);
  console.log(`     cd ../../../magneta-finance-contracts`);
  console.log(`     BATCH=scripts/safe/${path.basename(batchPath)} \\`);
  console.log(`       pnpm hardhat run scripts/safe/inhouse/execBatch.ts --network ${network.name}`);
  console.log(`2. After all 19 chains are done, patch tokens repo`);
  console.log(`   lib/constants/gatewayChains.ts:`);
  console.log(`     chainId ${chainId} → oftStandardFactory: '${newFactory}'`);
}

main().catch((err) => { console.error(err); process.exit(1); });
